travis: disable tests in osx
Tests in osx fail, apparently because the sha1sum command is not
available:

ERROR: could not spawn `sha1sum multiblock.vtm`: no such file or
directory (ENOENT)